/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as abletonRacks from "../abletonRacks.js";
import type * as accessControl from "../accessControl.js";
import type * as achievements from "../achievements.js";
import type * as admin_featureDiscovery from "../admin/featureDiscovery.js";
import type * as adminAnalytics from "../adminAnalytics.js";
import type * as adminEmailMonitoring from "../adminEmailMonitoring.js";
import type * as adminSetup from "../adminSetup.js";
import type * as affiliates from "../affiliates.js";
import type * as aiAgents from "../aiAgents.js";
import type * as aiConversations from "../aiConversations.js";
import type * as aiCourseBuilder from "../aiCourseBuilder.js";
import type * as aiCourseBuilderQueries from "../aiCourseBuilderQueries.js";
import type * as aiEmailGenerator from "../aiEmailGenerator.js";
import type * as aiMemories from "../aiMemories.js";
import type * as aiMessageFeedback from "../aiMessageFeedback.js";
import type * as aiPlatform_contentFlywheel from "../aiPlatform/contentFlywheel.js";
import type * as analytics_creatorPipeline from "../analytics/creatorPipeline.js";
import type * as analytics_errors from "../analytics/errors.js";
import type * as analytics_funnels from "../analytics/funnels.js";
import type * as analytics_kpis from "../analytics/kpis.js";
import type * as analytics from "../analytics.js";
import type * as analyticsSchema from "../analyticsSchema.js";
import type * as analyticsTracking from "../analyticsTracking.js";
import type * as audioGeneration from "../audioGeneration.js";
import type * as audioGenerationNode from "../audioGenerationNode.js";
import type * as automation from "../automation.js";
import type * as automations from "../automations.js";
import type * as blog from "../blog.js";
import type * as bundles from "../bundles.js";
import type * as campaigns from "../campaigns.js";
import type * as certificates from "../certificates.js";
import type * as certificatesSchema from "../certificatesSchema.js";
import type * as clerkSync from "../clerkSync.js";
import type * as coachingDiscordActions from "../coachingDiscordActions.js";
import type * as coachingEmails from "../coachingEmails.js";
import type * as coachingProducts from "../coachingProducts.js";
import type * as coachingSessionManager from "../coachingSessionManager.js";
import type * as coachingSessionQueries from "../coachingSessionQueries.js";
import type * as collaborativeNotes from "../collaborativeNotes.js";
import type * as contentGeneration from "../contentGeneration.js";
import type * as copyright from "../copyright.js";
import type * as copyrightEmails from "../copyrightEmails.js";
import type * as coupons from "../coupons.js";
import type * as courseNotificationQueries from "../courseNotificationQueries.js";
import type * as courseNotifications from "../courseNotifications.js";
import type * as courses from "../courses.js";
import type * as creatorPlans from "../creatorPlans.js";
import type * as creditPackageQueries from "../creditPackageQueries.js";
import type * as creditPackageStripe from "../creditPackageStripe.js";
import type * as credits from "../credits.js";
import type * as crons from "../crons.js";
import type * as customDomains from "../customDomains.js";
import type * as customers from "../customers.js";
import type * as debug_checkEnrollments from "../debug/checkEnrollments.js";
import type * as debug_userEnrollments from "../debug/userEnrollments.js";
import type * as debug from "../debug.js";
import type * as debugFix from "../debugFix.js";
import type * as devSeeders from "../devSeeders.js";
import type * as digitalProducts from "../digitalProducts.js";
import type * as discord from "../discord.js";
import type * as discordInternal from "../discordInternal.js";
import type * as discordPublic from "../discordPublic.js";
import type * as discordSchema from "../discordSchema.js";
import type * as domainVerification from "../domainVerification.js";
import type * as dripCampaignActions from "../dripCampaignActions.js";
import type * as dripCampaigns from "../dripCampaigns.js";
import type * as emailABTesting from "../emailABTesting.js";
import type * as emailAnalyticsRollup from "../emailAnalyticsRollup.js";
import type * as emailCampaigns from "../emailCampaigns.js";
import type * as emailContactSync from "../emailContactSync.js";
import type * as emailContacts from "../emailContacts.js";
import type * as emailCopyGenerator from "../emailCopyGenerator.js";
import type * as emailDomainSchema from "../emailDomainSchema.js";
import type * as emailHealthMonitoring from "../emailHealthMonitoring.js";
import type * as emailLeadScoring from "../emailLeadScoring.js";
import type * as emailQueries from "../emailQueries.js";
import type * as emailRepliesSchema from "../emailRepliesSchema.js";
import type * as emailSchema from "../emailSchema.js";
import type * as emailSegmentation from "../emailSegmentation.js";
import type * as emailSpamScoring from "../emailSpamScoring.js";
import type * as emailTags from "../emailTags.js";
import type * as emailTemplates from "../emailTemplates.js";
import type * as emailUnsubscribe from "../emailUnsubscribe.js";
import type * as emailWorkflows from "../emailWorkflows.js";
import type * as emails from "../emails.js";
import type * as embeddingActions from "../embeddingActions.js";
import type * as embeddings from "../embeddings.js";
import type * as enhancePluginDescriptions from "../enhancePluginDescriptions.js";
import type * as fanCountAggregation from "../fanCountAggregation.js";
import type * as files from "../files.js";
import type * as fixAccounts from "../fixAccounts.js";
import type * as fixes_bulkEnrollmentFix from "../fixes/bulkEnrollmentFix.js";
import type * as fixes_enrollmentSync from "../fixes/enrollmentSync.js";
import type * as followGateSubmissions from "../followGateSubmissions.js";
import type * as helpers_socialMediaHelpers from "../helpers/socialMediaHelpers.js";
import type * as http from "../http.js";
import type * as importFans from "../importFans.js";
import type * as importPlugins from "../importPlugins.js";
import type * as inboxActions from "../inboxActions.js";
import type * as inboxHelpers from "../inboxHelpers.js";
import type * as inboxQueries from "../inboxQueries.js";
import type * as inboxSync from "../inboxSync.js";
import type * as instagram_debug from "../instagram_debug.js";
import type * as integrations_blotato from "../integrations/blotato.js";
import type * as integrations_instagram from "../integrations/instagram.js";
import type * as integrations_internal from "../integrations/internal.js";
import type * as integrations_queries from "../integrations/queries.js";
import type * as langchainNotes from "../langchainNotes.js";
import type * as langchainNotesActions from "../langchainNotesActions.js";
import type * as leadMagnetAnalysisMutations from "../leadMagnetAnalysisMutations.js";
import type * as leadSubmissions from "../leadSubmissions.js";
import type * as leaderboards from "../leaderboards.js";
import type * as lib_typeValidation from "../lib/typeValidation.js";
import type * as lib_utils from "../lib/utils.js";
import type * as library from "../library.js";
import type * as libraryHelpers from "../libraryHelpers.js";
import type * as linkInBio from "../linkInBio.js";
import type * as liveViewers from "../liveViewers.js";
import type * as marketplace from "../marketplace.js";
import type * as masterAI_critic from "../masterAI/critic.js";
import type * as masterAI_factVerifier from "../masterAI/factVerifier.js";
import type * as masterAI_finalWriter from "../masterAI/finalWriter.js";
import type * as masterAI_goalExtractor from "../masterAI/goalExtractor.js";
import type * as masterAI_goalExtractorMutations from "../masterAI/goalExtractorMutations.js";
import type * as masterAI_ideaGenerator from "../masterAI/ideaGenerator.js";
import type * as masterAI_index from "../masterAI/index.js";
import type * as masterAI_leadMagnetAnalyzer from "../masterAI/leadMagnetAnalyzer.js";
import type * as masterAI_llmClient from "../masterAI/llmClient.js";
import type * as masterAI_memoryManager from "../masterAI/memoryManager.js";
import type * as masterAI_mutations from "../masterAI/mutations.js";
import type * as masterAI_planner from "../masterAI/planner.js";
import type * as masterAI_platformKnowledge from "../masterAI/platformKnowledge.js";
import type * as masterAI_queries from "../masterAI/queries.js";
import type * as masterAI_retriever from "../masterAI/retriever.js";
import type * as masterAI_socialMediaGenerator from "../masterAI/socialMediaGenerator.js";
import type * as masterAI_summarizer from "../masterAI/summarizer.js";
import type * as masterAI_tools_blotato from "../masterAI/tools/blotato.js";
import type * as masterAI_tools_executor from "../masterAI/tools/executor.js";
import type * as masterAI_tools_mutations from "../masterAI/tools/mutations.js";
import type * as masterAI_types from "../masterAI/types.js";
import type * as masterAI_webResearch from "../masterAI/webResearch.js";
import type * as memberships from "../memberships.js";
import type * as migrations_backfillCourseCustomers from "../migrations/backfillCourseCustomers.js";
import type * as migrations_backfillCustomers from "../migrations/backfillCustomers.js";
import type * as migrations_importPlugins from "../migrations/importPlugins.js";
import type * as migrations_migrateAbletonRacksToEffectChains from "../migrations/migrateAbletonRacksToEffectChains.js";
import type * as migrations_universalProductsMigration from "../migrations/universalProductsMigration.js";
import type * as mixingTemplates from "../mixingTemplates.js";
import type * as model_courses from "../model/courses.js";
import type * as monetizationSchema from "../monetizationSchema.js";
import type * as monetizationUtils from "../monetizationUtils.js";
import type * as musicShowcase from "../musicShowcase.js";
import type * as noteTemplates from "../noteTemplates.js";
import type * as notes from "../notes.js";
import type * as notesToCourse from "../notesToCourse.js";
import type * as notificationPreferences from "../notificationPreferences.js";
import type * as notifications from "../notifications.js";
import type * as packSamples from "../packSamples.js";
import type * as paymentPlans from "../paymentPlans.js";
import type * as playlists from "../playlists.js";
import type * as pluginVideoGeneration from "../pluginVideoGeneration.js";
import type * as plugins from "../plugins.js";
import type * as productAI from "../productAI.js";
import type * as purchases from "../purchases.js";
import type * as qa from "../qa.js";
import type * as qaSchema from "../qaSchema.js";
import type * as quizzes from "../quizzes.js";
import type * as quizzesSchema from "../quizzesSchema.js";
import type * as rag from "../rag.js";
import type * as ragActions from "../ragActions.js";
import type * as recommendations from "../recommendations.js";
import type * as reports from "../reports.js";
import type * as resendDomainHelpers from "../resendDomainHelpers.js";
import type * as resendDomainSync from "../resendDomainSync.js";
import type * as sampleGeneration from "../sampleGeneration.js";
import type * as samplePacks from "../samplePacks.js";
import type * as samples from "../samples.js";
import type * as scriptIllustrationMutations from "../scriptIllustrationMutations.js";
import type * as scriptIllustrationQueries from "../scriptIllustrationQueries.js";
import type * as scriptIllustrationSearch from "../scriptIllustrationSearch.js";
import type * as scriptIllustrations from "../scriptIllustrations.js";
import type * as seedCreditPackages from "../seedCreditPackages.js";
import type * as sendTimeOptimization from "../sendTimeOptimization.js";
import type * as socialDM from "../socialDM.js";
import type * as socialDMQueries from "../socialDMQueries.js";
import type * as socialDMWebhooks from "../socialDMWebhooks.js";
import type * as socialMedia from "../socialMedia.js";
import type * as socialMediaActions from "../socialMediaActions.js";
import type * as socialMediaPosts from "../socialMediaPosts.js";
import type * as socialPostEmbeddings from "../socialPostEmbeddings.js";
import type * as socialPostEmbeddingsMutations from "../socialPostEmbeddingsMutations.js";
import type * as stats from "../stats.js";
import type * as storeStats from "../storeStats.js";
import type * as stores from "../stores.js";
import type * as submissions from "../submissions.js";
import type * as subscriptions from "../subscriptions.js";
import type * as tracks from "../tracks.js";
import type * as universalProducts from "../universalProducts.js";
import type * as universalProductsExamples from "../universalProductsExamples.js";
import type * as userLibrary from "../userLibrary.js";
import type * as users from "../users.js";
import type * as vercelDomainManager from "../vercelDomainManager.js";
import type * as webhooks_facebook from "../webhooks/facebook.js";
import type * as webhooks_instagram from "../webhooks/instagram.js";
import type * as webhooks_twitter from "../webhooks/twitter.js";
import type * as wishlists from "../wishlists.js";
import type * as workflowActions from "../workflowActions.js";
import type * as workflowHelpers from "../workflowHelpers.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  abletonRacks: typeof abletonRacks;
  accessControl: typeof accessControl;
  achievements: typeof achievements;
  "admin/featureDiscovery": typeof admin_featureDiscovery;
  adminAnalytics: typeof adminAnalytics;
  adminEmailMonitoring: typeof adminEmailMonitoring;
  adminSetup: typeof adminSetup;
  affiliates: typeof affiliates;
  aiAgents: typeof aiAgents;
  aiConversations: typeof aiConversations;
  aiCourseBuilder: typeof aiCourseBuilder;
  aiCourseBuilderQueries: typeof aiCourseBuilderQueries;
  aiEmailGenerator: typeof aiEmailGenerator;
  aiMemories: typeof aiMemories;
  aiMessageFeedback: typeof aiMessageFeedback;
  "aiPlatform/contentFlywheel": typeof aiPlatform_contentFlywheel;
  "analytics/creatorPipeline": typeof analytics_creatorPipeline;
  "analytics/errors": typeof analytics_errors;
  "analytics/funnels": typeof analytics_funnels;
  "analytics/kpis": typeof analytics_kpis;
  analytics: typeof analytics;
  analyticsSchema: typeof analyticsSchema;
  analyticsTracking: typeof analyticsTracking;
  audioGeneration: typeof audioGeneration;
  audioGenerationNode: typeof audioGenerationNode;
  automation: typeof automation;
  automations: typeof automations;
  blog: typeof blog;
  bundles: typeof bundles;
  campaigns: typeof campaigns;
  certificates: typeof certificates;
  certificatesSchema: typeof certificatesSchema;
  clerkSync: typeof clerkSync;
  coachingDiscordActions: typeof coachingDiscordActions;
  coachingEmails: typeof coachingEmails;
  coachingProducts: typeof coachingProducts;
  coachingSessionManager: typeof coachingSessionManager;
  coachingSessionQueries: typeof coachingSessionQueries;
  collaborativeNotes: typeof collaborativeNotes;
  contentGeneration: typeof contentGeneration;
  copyright: typeof copyright;
  copyrightEmails: typeof copyrightEmails;
  coupons: typeof coupons;
  courseNotificationQueries: typeof courseNotificationQueries;
  courseNotifications: typeof courseNotifications;
  courses: typeof courses;
  creatorPlans: typeof creatorPlans;
  creditPackageQueries: typeof creditPackageQueries;
  creditPackageStripe: typeof creditPackageStripe;
  credits: typeof credits;
  crons: typeof crons;
  customDomains: typeof customDomains;
  customers: typeof customers;
  "debug/checkEnrollments": typeof debug_checkEnrollments;
  "debug/userEnrollments": typeof debug_userEnrollments;
  debug: typeof debug;
  debugFix: typeof debugFix;
  devSeeders: typeof devSeeders;
  digitalProducts: typeof digitalProducts;
  discord: typeof discord;
  discordInternal: typeof discordInternal;
  discordPublic: typeof discordPublic;
  discordSchema: typeof discordSchema;
  domainVerification: typeof domainVerification;
  dripCampaignActions: typeof dripCampaignActions;
  dripCampaigns: typeof dripCampaigns;
  emailABTesting: typeof emailABTesting;
  emailAnalyticsRollup: typeof emailAnalyticsRollup;
  emailCampaigns: typeof emailCampaigns;
  emailContactSync: typeof emailContactSync;
  emailContacts: typeof emailContacts;
  emailCopyGenerator: typeof emailCopyGenerator;
  emailDomainSchema: typeof emailDomainSchema;
  emailHealthMonitoring: typeof emailHealthMonitoring;
  emailLeadScoring: typeof emailLeadScoring;
  emailQueries: typeof emailQueries;
  emailRepliesSchema: typeof emailRepliesSchema;
  emailSchema: typeof emailSchema;
  emailSegmentation: typeof emailSegmentation;
  emailSpamScoring: typeof emailSpamScoring;
  emailTags: typeof emailTags;
  emailTemplates: typeof emailTemplates;
  emailUnsubscribe: typeof emailUnsubscribe;
  emailWorkflows: typeof emailWorkflows;
  emails: typeof emails;
  embeddingActions: typeof embeddingActions;
  embeddings: typeof embeddings;
  enhancePluginDescriptions: typeof enhancePluginDescriptions;
  fanCountAggregation: typeof fanCountAggregation;
  files: typeof files;
  fixAccounts: typeof fixAccounts;
  "fixes/bulkEnrollmentFix": typeof fixes_bulkEnrollmentFix;
  "fixes/enrollmentSync": typeof fixes_enrollmentSync;
  followGateSubmissions: typeof followGateSubmissions;
  "helpers/socialMediaHelpers": typeof helpers_socialMediaHelpers;
  http: typeof http;
  importFans: typeof importFans;
  importPlugins: typeof importPlugins;
  inboxActions: typeof inboxActions;
  inboxHelpers: typeof inboxHelpers;
  inboxQueries: typeof inboxQueries;
  inboxSync: typeof inboxSync;
  instagram_debug: typeof instagram_debug;
  "integrations/blotato": typeof integrations_blotato;
  "integrations/instagram": typeof integrations_instagram;
  "integrations/internal": typeof integrations_internal;
  "integrations/queries": typeof integrations_queries;
  langchainNotes: typeof langchainNotes;
  langchainNotesActions: typeof langchainNotesActions;
  leadMagnetAnalysisMutations: typeof leadMagnetAnalysisMutations;
  leadSubmissions: typeof leadSubmissions;
  leaderboards: typeof leaderboards;
  "lib/typeValidation": typeof lib_typeValidation;
  "lib/utils": typeof lib_utils;
  library: typeof library;
  libraryHelpers: typeof libraryHelpers;
  linkInBio: typeof linkInBio;
  liveViewers: typeof liveViewers;
  marketplace: typeof marketplace;
  "masterAI/critic": typeof masterAI_critic;
  "masterAI/factVerifier": typeof masterAI_factVerifier;
  "masterAI/finalWriter": typeof masterAI_finalWriter;
  "masterAI/goalExtractor": typeof masterAI_goalExtractor;
  "masterAI/goalExtractorMutations": typeof masterAI_goalExtractorMutations;
  "masterAI/ideaGenerator": typeof masterAI_ideaGenerator;
  "masterAI/index": typeof masterAI_index;
  "masterAI/leadMagnetAnalyzer": typeof masterAI_leadMagnetAnalyzer;
  "masterAI/llmClient": typeof masterAI_llmClient;
  "masterAI/memoryManager": typeof masterAI_memoryManager;
  "masterAI/mutations": typeof masterAI_mutations;
  "masterAI/planner": typeof masterAI_planner;
  "masterAI/platformKnowledge": typeof masterAI_platformKnowledge;
  "masterAI/queries": typeof masterAI_queries;
  "masterAI/retriever": typeof masterAI_retriever;
  "masterAI/socialMediaGenerator": typeof masterAI_socialMediaGenerator;
  "masterAI/summarizer": typeof masterAI_summarizer;
  "masterAI/tools/blotato": typeof masterAI_tools_blotato;
  "masterAI/tools/executor": typeof masterAI_tools_executor;
  "masterAI/tools/mutations": typeof masterAI_tools_mutations;
  "masterAI/types": typeof masterAI_types;
  "masterAI/webResearch": typeof masterAI_webResearch;
  memberships: typeof memberships;
  "migrations/backfillCourseCustomers": typeof migrations_backfillCourseCustomers;
  "migrations/backfillCustomers": typeof migrations_backfillCustomers;
  "migrations/importPlugins": typeof migrations_importPlugins;
  "migrations/migrateAbletonRacksToEffectChains": typeof migrations_migrateAbletonRacksToEffectChains;
  "migrations/universalProductsMigration": typeof migrations_universalProductsMigration;
  mixingTemplates: typeof mixingTemplates;
  "model/courses": typeof model_courses;
  monetizationSchema: typeof monetizationSchema;
  monetizationUtils: typeof monetizationUtils;
  musicShowcase: typeof musicShowcase;
  noteTemplates: typeof noteTemplates;
  notes: typeof notes;
  notesToCourse: typeof notesToCourse;
  notificationPreferences: typeof notificationPreferences;
  notifications: typeof notifications;
  packSamples: typeof packSamples;
  paymentPlans: typeof paymentPlans;
  playlists: typeof playlists;
  pluginVideoGeneration: typeof pluginVideoGeneration;
  plugins: typeof plugins;
  productAI: typeof productAI;
  purchases: typeof purchases;
  qa: typeof qa;
  qaSchema: typeof qaSchema;
  quizzes: typeof quizzes;
  quizzesSchema: typeof quizzesSchema;
  rag: typeof rag;
  ragActions: typeof ragActions;
  recommendations: typeof recommendations;
  reports: typeof reports;
  resendDomainHelpers: typeof resendDomainHelpers;
  resendDomainSync: typeof resendDomainSync;
  sampleGeneration: typeof sampleGeneration;
  samplePacks: typeof samplePacks;
  samples: typeof samples;
  scriptIllustrationMutations: typeof scriptIllustrationMutations;
  scriptIllustrationQueries: typeof scriptIllustrationQueries;
  scriptIllustrationSearch: typeof scriptIllustrationSearch;
  scriptIllustrations: typeof scriptIllustrations;
  seedCreditPackages: typeof seedCreditPackages;
  sendTimeOptimization: typeof sendTimeOptimization;
  socialDM: typeof socialDM;
  socialDMQueries: typeof socialDMQueries;
  socialDMWebhooks: typeof socialDMWebhooks;
  socialMedia: typeof socialMedia;
  socialMediaActions: typeof socialMediaActions;
  socialMediaPosts: typeof socialMediaPosts;
  socialPostEmbeddings: typeof socialPostEmbeddings;
  socialPostEmbeddingsMutations: typeof socialPostEmbeddingsMutations;
  stats: typeof stats;
  storeStats: typeof storeStats;
  stores: typeof stores;
  submissions: typeof submissions;
  subscriptions: typeof subscriptions;
  tracks: typeof tracks;
  universalProducts: typeof universalProducts;
  universalProductsExamples: typeof universalProductsExamples;
  userLibrary: typeof userLibrary;
  users: typeof users;
  vercelDomainManager: typeof vercelDomainManager;
  "webhooks/facebook": typeof webhooks_facebook;
  "webhooks/instagram": typeof webhooks_instagram;
  "webhooks/twitter": typeof webhooks_twitter;
  wishlists: typeof wishlists;
  workflowActions: typeof workflowActions;
  workflowHelpers: typeof workflowHelpers;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
