import React from "react";
import {
  View,
  Text,
  Svg,
  Rect,
  Circle,
  Defs,
  LinearGradient,
  Stop,
} from "@react-pdf/renderer";
import { styles, BRAND } from "./styles";

// =============================================================================
// Types (matching existing Outline schema)
// =============================================================================

export interface OutlineItem {
  text: string;
  subItems?: string[];
  isTip?: boolean;
  isWarning?: boolean;
}

export interface OutlineSection {
  heading: string;
  type: string;
  items: OutlineItem[];
}

// =============================================================================
// TYPE LABEL MAPPING
// =============================================================================

const TYPE_LABELS: Record<string, string> = {
  key_takeaways: "KEY TAKEAWAYS",
  quick_reference: "QUICK REFERENCE",
  step_by_step: "STEP BY STEP",
  tips: "PRO TIPS",
  comparison: "COMPARISON",
  glossary: "GLOSSARY",
  custom: "REFERENCE",
};

// =============================================================================
// COVER PAGE
// =============================================================================

interface CoverPageProps {
  title: string;
  subtitle?: string;
  badgeText?: string;
}

export const CoverPage: React.FC<CoverPageProps> = ({ title, subtitle, badgeText = "REFERENCE GUIDE" }) => (
  <View>
    {/* Decorative gradient header */}
    <Svg viewBox="0 0 595 380" style={{ width: "100%", height: 380 }}>
      <Defs>
        <LinearGradient id="headerGrad" x1="0" y1="0" x2="1" y2="1">
          <Stop offset="0%" stopColor={BRAND.primaryDark} />
          <Stop offset="100%" stopColor="#312E81" />
        </LinearGradient>
      </Defs>
      <Rect x="0" y="0" width="595" height="380" fill="url(#headerGrad)" />
      {/* Decorative circles */}
      <Circle cx="520" cy="60" r="120" fill={BRAND.primary} opacity="0.12" />
      <Circle cx="480" cy="320" r="80" fill={BRAND.primaryMid} opacity="0.08" />
      <Circle cx="80" cy="340" r="50" fill={BRAND.primaryMid} opacity="0.06" />
      {/* Accent bar at top */}
      <Rect x="0" y="0" width="595" height="4" fill={BRAND.primaryMid} />
    </Svg>

    {/* Overlay text on top of the SVG header */}
    <View
      style={{
        position: "absolute",
        top: 80,
        left: 48,
        right: 48,
      }}
    >
      <Text style={styles.coverBrandLabel}>PPR ACADEMY</Text>
      <Text style={styles.coverTitle}>{title}</Text>
      {subtitle && <Text style={styles.coverSubtitle}>{subtitle}</Text>}
      <View style={styles.coverBadge}>
        <Text style={styles.coverBadgeText}>{badgeText}</Text>
      </View>
    </View>

    {/* Footer area */}
    <View style={styles.coverFooter}>
      <Text style={styles.coverFooterText}>
        {"Generated by "}
        <Text style={styles.coverFooterUrl}>ppr.academy</Text>
      </Text>
    </View>
  </View>
);

// =============================================================================
// TABLE OF CONTENTS
// =============================================================================

interface TableOfContentsProps {
  sections: OutlineSection[];
}

export const TableOfContents: React.FC<TableOfContentsProps> = ({
  sections,
}) => (
  <View>
    <Text style={styles.tocTitle}>Contents</Text>
    {sections.map((section, i) => (
      <View key={i} style={styles.tocItem}>
        <View style={styles.tocBullet} />
        <Text style={styles.tocTypeLabel}>
          {TYPE_LABELS[section.type] || section.type.toUpperCase()}
        </Text>
        <Text style={styles.tocHeading}>{section.heading}</Text>
      </View>
    ))}
  </View>
);

// =============================================================================
// SECTION HEADER
// =============================================================================

interface SectionHeaderProps {
  heading: string;
  type: string;
}

export const SectionHeader: React.FC<SectionHeaderProps> = ({
  heading,
  type,
}) => (
  <View style={styles.sectionHeaderWrap} minPresenceAhead={80} wrap={false}>
    <Text style={styles.sectionTypeLabel}>
      {TYPE_LABELS[type] || type.toUpperCase()}
    </Text>
    <Text style={styles.sectionHeading}>{heading}</Text>
    <View style={styles.sectionDivider} />
  </View>
);

// =============================================================================
// BULLET ITEM
// =============================================================================

interface BulletItemProps {
  text: string;
  subItems?: string[];
}

export const BulletItem: React.FC<BulletItemProps> = ({ text, subItems }) => (
  <View wrap={false}>
    <View style={styles.bulletItemRow}>
      <View style={styles.bulletDot} />
      <View style={styles.bulletTextWrap}>
        <Text style={styles.bulletText}>{text}</Text>
      </View>
    </View>
    {subItems &&
      subItems.map((sub, i) => (
        <View key={i} style={styles.subItemRow}>
          <Text style={styles.subItemDash}>-</Text>
          <Text style={styles.subItemText}>{sub}</Text>
        </View>
      ))}
  </View>
);

// =============================================================================
// NUMBERED ITEM
// =============================================================================

interface NumberedItemProps {
  number: number;
  text: string;
  subItems?: string[];
}

export const NumberedItem: React.FC<NumberedItemProps> = ({
  number,
  text,
  subItems,
}) => (
  <View wrap={false}>
    <View style={styles.numberedItemRow}>
      <View style={styles.numberBadge}>
        <Text style={styles.numberText}>{number}</Text>
      </View>
      <View style={styles.bulletTextWrap}>
        <Text style={styles.bulletText}>{text}</Text>
      </View>
    </View>
    {subItems &&
      subItems.map((sub, i) => (
        <View key={i} style={styles.subItemRow}>
          <Text style={styles.subItemDash}>-</Text>
          <Text style={styles.subItemText}>{sub}</Text>
        </View>
      ))}
  </View>
);

// =============================================================================
// TIP BOX
// =============================================================================

interface TipBoxProps {
  text: string;
  subItems?: string[];
}

export const TipBox: React.FC<TipBoxProps> = ({ text, subItems }) => (
  <View style={styles.tipBox} wrap={false}>
    <Text style={styles.tipLabel}>TIP</Text>
    <Text style={styles.tipText}>{text}</Text>
    {subItems &&
      subItems.map((sub, i) => (
        <View key={i} style={{ ...styles.subItemRow, paddingLeft: 0 }}>
          <Text style={styles.subItemDash}>-</Text>
          <Text style={styles.subItemText}>{sub}</Text>
        </View>
      ))}
  </View>
);

// =============================================================================
// WARNING BOX
// =============================================================================

interface WarningBoxProps {
  text: string;
  subItems?: string[];
}

export const WarningBox: React.FC<WarningBoxProps> = ({ text, subItems }) => (
  <View style={styles.warningBox} wrap={false}>
    <Text style={styles.warningLabel}>WARNING</Text>
    <Text style={styles.warningText}>{text}</Text>
    {subItems &&
      subItems.map((sub, i) => (
        <View key={i} style={{ ...styles.subItemRow, paddingLeft: 0 }}>
          <Text style={styles.subItemDash}>-</Text>
          <Text style={styles.subItemText}>{sub}</Text>
        </View>
      ))}
  </View>
);

// =============================================================================
// PAGE FOOTER (fixed on every page)
// =============================================================================

interface PageFooterProps {
  text?: string;
}

export const PageFooter: React.FC<PageFooterProps> = ({
  text = "PPR Academy — ppr.academy",
}) => (
  <View style={styles.pageFooter} fixed>
    <Text style={styles.pageFooterText}>{text}</Text>
    <Text
      style={styles.pageNumber}
      render={({ pageNumber, totalPages }) =>
        `${pageNumber} / ${totalPages}`
      }
    />
  </View>
);
